version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: ${PROJECT_NAME:-vanilla-genai}-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db/scripts:/scripts
      - ./db/snapshot:/docker-entrypoint-initdb.d/snapshots
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-vanilla_genai}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
