services:
  # Supabase PostgreSQL Database
  supabase-db:
    image: supabase/postgres:15.8.1.054
    container_name: ${PROJECT_NAME}-supabase-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SUPABASE_DB_USER}
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
      POSTGRES_DB: ${SUPABASE_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_LISTEN_ADDRESSES: "*"
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
      - ./supabase/db/snapshot:/snapshot
      - ./supabase/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./supabase/db/backup.sh:/usr/local/bin/backup.sh
      - ./supabase/db/restore.sh:/usr/local/bin/restore.sh
    command: postgres -c listen_addresses='*' -c hba_file=/var/lib/postgresql/data/pg_hba.conf
    ports:
      - "${SUPABASE_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${SUPABASE_DB_USER} -d ${SUPABASE_DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend

  # Supabase Meta Service for DB Management
  supabase-meta:
    image: supabase/postgres-meta:v0.66.3
    container_name: ${PROJECT_NAME}-supabase-meta
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${SUPABASE_DB_NAME}
      PG_META_DB_USER: ${SUPABASE_DB_USER}
      PG_META_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
    ports:
      - "${SUPABASE_META_PORT}:8080"
    networks:
      - backend

  # Supabase Studio (Dashboard)
  supabase-studio:
    image: supabase/studio:latest
    container_name: ${PROJECT_NAME}-supabase-studio
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
      supabase-meta:
        condition: service_started
    env_file:
      - .env
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      SUPABASE_URL: http://localhost:${SUPABASE_STUDIO_PORT}
      SUPABASE_PUBLIC_URL: http://localhost:${SUPABASE_STUDIO_PORT}
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
      DEFAULT_ORGANIZATION_NAME: ${PROJECT_NAME}
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
    ports:
      - "${SUPABASE_STUDIO_PORT}:3000"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:3000"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend
      
  graph-db:
    build:
      context: ./graph-db
    container_name: ${PROJECT_NAME}-graph-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${GRAPH_DB_AUTH}
      # This advertises the correct address for internal container usage
      NEO4J_server_default__advertised__address: "localhost"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # Enable APOC plugin for advanced operations
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      # Configure browser connection to use the internal Bolt connector
      NEO4J_browser_remote__content__hostname__whitelist: "*"
    ports:
      - "${GRAPH_DB_PORT}:7687" # Bolt port
      - "${GRAPH_DB_DASHBOARD_PORT}:7474" # HTTP port (dashboard)
    volumes:
      - ./graph-db/scripts:/scripts
      - ./graph-db/snapshot:/snapshot
      - graph-db-data:/data
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:7474"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend

  # Ollama Model Puller - connects to the host's Ollama instance and pulls models from supabase
  ollama-pull:
    image: alpine:latest
    container_name: ${PROJECT_NAME}-ollama-pull
    restart: "no"
    depends_on:
      - supabase-db
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host machine from container
    environment:
      PGHOST: supabase-db
      PGPORT: 5432
      PGDATABASE: ${SUPABASE_DB_NAME}
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
    networks:
      - backend
    entrypoint: sh
    command: >
      -c "
      echo 'Installing required tools...' &&
      apk add --no-cache curl postgresql-client &&
      echo 'Waiting 10 seconds before connecting to host Ollama...' &&
      sleep 10 &&
      echo 'Checking if host Ollama is available...' &&
      until curl -s --fail http://host.docker.internal:11434/; do
        echo 'Waiting for host Ollama API...'
        sleep 5
      done &&
      echo 'Fetching active Ollama models from database...' &&
      MODEL_LIST=$(PGPASSWORD=${SUPABASE_DB_PASSWORD} psql -h supabase-db -p 5432 -d ${SUPABASE_DB_NAME} -U ${SUPABASE_DB_USER} -t -c \"SELECT name FROM llms WHERE provider = 'ollama' AND active = true;\") &&
      if [ -z \"$${MODEL_LIST}\" ]; then
        echo 'No active Ollama models found in database.'
      else
        for MODEL in $${MODEL_LIST}; do
          MODEL_CLEAN=$(echo $${MODEL} | tr -d ' ') &&
          echo \"Pulling $${MODEL_CLEAN} model...\" &&
          curl -s -X POST http://host.docker.internal:11434/api/pull -d '{\"name\":\"'$${MODEL_CLEAN}'\"}' 
          echo
        done
      fi
      "

# OpenWebUI - UI for Local Ollama
  open-web-ui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ${PROJECT_NAME}-open-web-ui
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
      ollama-pull:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Access host machine from container
    env_file:
      - .env
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - DATABASE_URL=postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      - WEBUI_SECRET_KEY=${OPEN_WEB_UI_SECRET_KEY}
    volumes:
      - open-web-ui-data:/data
    ports:
      - "${OPEN_WEB_UI_PORT}:8080"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:8080"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  supabase-db-data:
    driver: local
  graph-db-data:
    driver: local
  open-web-ui-data:
    driver: local