services:
  supabase-db:
    image: supabase/postgres:17.4.1.016
    container_name: ${PROJECT_NAME}-supabase-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${SUPABASE_DB_USER}
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
      POSTGRES_DB: ${SUPABASE_DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - supabase-db-data:/var/lib/postgresql/data
      - ./supabase/db/snapshot:/snapshot
    ports:
      - "${SUPABASE_DB_PORT}:5432"
    networks:
      - backend-bridge-network

  supabase-db-init:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-supabase-db-init
    restart: no
    env_file:
      - .env
    environment:
      PGHOST: supabase-db
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
      PGDATABASE: ${SUPABASE_DB_NAME}
    volumes:
      - ./supabase/db/scripts:/scripts
    entrypoint: ["/scripts/db-init-runner.sh"]
    depends_on:
      - supabase-db
    networks:
      - backend-bridge-network

  supabase-meta:
    image: supabase/postgres-meta:v0.88.9
    container_name: ${PROJECT_NAME}-supabase-meta
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: supabase-db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: ${SUPABASE_DB_NAME}
      PG_META_DB_USER: ${SUPABASE_DB_USER}
      PG_META_DB_PASSWORD: ${SUPABASE_DB_PASSWORD}
    ports:
      - "${SUPABASE_META_PORT}:8080"
    networks:
      - backend-bridge-network

  kong-api-gateway:
    container_name: ${PROJECT_NAME}-kong-api-gateway
    image: kong:3.9.0
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${KONG_HTTP_PORT}:8000/tcp
      - ${KONG_HTTPS_PORT}:8443/tcp
    volumes:
      - ./volumes/api/kong.yml:/home/kong/kong.yml:ro,z
    depends_on:
      supabase-auth:
        condition: service_started
      supabase-api:
        condition: service_started
      supabase-storage:
        condition: service_started
      supabase-meta:
        condition: service_started
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
    networks:
      - backend-bridge-network

  supabase-storage:
    image: supabase/storage-api:v1.22.7
    container_name: ${PROJECT_NAME}-supabase-storage
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      JWT_SECRET: ${SUPABASE_JWT_SECRET}
      ANON_KEY: ${SUPABASE_ANON_KEY}
      SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      REGION: ${STORAGE_REGION}
      FILE_SIZE_LIMIT: ${STORAGE_FILE_SIZE_LIMIT}
      STORAGE_BACKEND: ${STORAGE_BACKEND}
      FILE_STORAGE_PATH: /var/lib/storage
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: ${TENANT_ID}
      PROJECT_REF: ${PROJECT_REF}
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      POSTGREST_URL: http://supabase-api:3000
      GOTRUE_URL: http://supabase-auth:9999
    ports:
      - "${SUPABASE_STORAGE_PORT}:5000"
    volumes:
      - supabase-storage-data:/var/lib/storage
    networks:
      - backend-bridge-network

  supabase-auth:
    image: supabase/gotrue:v2.171.0
    container_name: ${PROJECT_NAME}-supabase-auth
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      GOTRUE_SITE_URL: http://supabase-studio:3000
      API_EXTERNAL_URL: http://supabase-auth:9999
      GOTRUE_DB_DRIVER: postgres
      DB_NAMESPACE: auth
      GOTRUE_DB_DATABASE_URL: postgres://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      GOTRUE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_MAILER_URLPATHS_INVITE: "/invite"
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: "/confirm"
      GOTRUE_MAILER_URLPATHS_RECOVERY: "/recover"
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "/email-change"
      GOTRUE_SMTP_HOST: "localhost"
      GOTRUE_SMTP_PORT: 1025
      GOTRUE_SMTP_USER: ""
      GOTRUE_SMTP_PASS: ""
      GOTRUE_SMTP_SENDER_NAME: "Supabase Auth"
      GOTRUE_SMTP_ADMIN_EMAIL: "admin@example.com"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_SITE_NAME: "Local Supabase"
    ports:
      - "${SUPABASE_AUTH_PORT}:9999"
    networks:
      - backend-bridge-network

  supabase-api:
    image: postgrest/postgrest:v12.2.10
    container_name: ${PROJECT_NAME}-supabase-api
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      PGRST_DB_URI: postgres://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      PGRST_DB_SCHEMA: "public,storage,auth"
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      PGRST_DB_USE_LEGACY_GUCS: "false"
    ports:
      - "${SUPABASE_API_PORT}:3000"
    networks:
      - backend-bridge-network

  supabase-studio:
    image: supabase/studio:latest
    container_name: ${PROJECT_NAME}-supabase-studio
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      supabase-meta:
        condition: service_started
      supabase-storage:
        condition: service_started
      supabase-auth:
        condition: service_started
      supabase-api:
        condition: service_started
      kong-api-gateway:
        condition: service_started
    env_file:
      - .env
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      SUPABASE_URL: http://kong-api-gateway:8000
      SUPABASE_PUBLIC_URL: http://localhost:${KONG_HTTP_PORT}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      DEFAULT_ORGANIZATION_NAME: ${PROJECT_NAME}
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      AUTH_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
    ports:
      - "${SUPABASE_STUDIO_PORT}:3000"
    networks:
      - backend-bridge-network

  neo4j-graph-db:
    build:
      context: ./graph-db
    container_name: ${PROJECT_NAME}-neo4j-graph-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NEO4J_AUTH: ${GRAPH_DB_AUTH}
      NEO4J_server_default__advertised__address: "neo4j-graph-db"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_browser_remote__content__hostname__whitelist: "*"
    ports:
      - "${GRAPH_DB_PORT}:7687"
      - "${GRAPH_DB_DASHBOARD_PORT}:7474"
    volumes:
      - ./graph-db/scripts:/scripts
      - ./graph-db/snapshot:/snapshot
      - graph-db-data:/data
    networks:
      - backend-bridge-network

  ollama-pull:
    image: alpine:latest
    container_name: ${PROJECT_NAME}-ollama-pull
    restart: "no"
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    networks:
      - backend-bridge-network
    environment:
      PGHOST: supabase-db
      PGPORT: 5432
      PGDATABASE: ${SUPABASE_DB_NAME}
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
      OLLAMA_HOST_URL: http://host.docker.internal:11434
    volumes:
      - ./ollama-pull/scripts:/scripts
    entrypoint: ["/scripts/pull.sh"]

  open-web-ui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: ${PROJECT_NAME}-open-web-ui
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      ollama-pull:
        condition: service_completed_successfully
      supabase-storage:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      WEBUI_SECRET_KEY: ${OPEN_WEB_UI_SECRET_KEY}
    volumes:
      - open-web-ui-data:/data
    ports:
      - "${OPEN_WEB_UI_PORT}:8080"
    networks:
      - backend-bridge-network

  backend:
    build:
      context: ./backend
    container_name: ${PROJECT_NAME}-backend
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      ollama-pull:
        condition: service_completed_successfully
      neo4j-graph-db:
        condition: service_started
      supabase-storage:
        condition: service_started
      kong-api-gateway:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      KONG_URL: http://kong-api-gateway:8000
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      NEO4J_URI: bolt://neo4j-graph-db:7687
      NEO4J_USER: ${GRAPH_DB_USER}
      NEO4J_PASSWORD: ${GRAPH_DB_PASSWORD}
    volumes:
      - ./backend/app:/app
      - backend-data:/app/data
    ports:
      - "${BACKEND_PORT}:8000"
    networks:
      - backend-bridge-network

networks:
  backend-bridge-network:
    driver: bridge

volumes:
  supabase-db-data:
    driver: local
  graph-db-data:
    driver: local
  open-web-ui-data:
    driver: local
  backend-data:
    driver: local
  supabase-storage-data:
    driver: local
