include:
  - compose-profiles/data.yml
  - compose-profiles/ai.yml
  - compose-profiles/apps.yml

networks:
  backend-bridge-network:
    driver: bridge

volumes:
  supabase-db-data:
    driver: local
  redis-data:
    driver: local
  graph-db-data:
    driver: local
  ollama-data:
    driver: local
  local-deep-researcher-data:
    driver: local
  open-web-ui-data:
    driver: local
  backend-data:
    driver: local
  supabase-storage-data:
    driver: local
  n8n-data:
    driver: local