[botdetection]
ipv4_prefix = 32
ipv6_prefix = 48
trusted_proxies = [
  '127.0.0.0/8',
  '::1'
]

[botdetection.ip_limit]
filter_link_local = false
link_token = false

[botdetection.ip_lists]
pass_ip = [
  '127.0.0.1/8',
  '::1/128'
]
block_ip = []
pass_searxng_org = true
