# SearxNG Configuration - Minimal Working Version
general:
  debug: false
  instance_name: "GenAI Stack Private Search"
  enable_metrics: true

search:
  max_request_timeout: 3.0
  safe_search: 0
  autocomplete: "duckduckgo"

server:
  secret_key: "${SEARXNG_SECRET}"
  limiter: true
  public_instance: false
  image_proxy: true
  default_theme: "simple"

redis:
  url: redis://:redis_password@redis:6379/1

ui:
  static_use_hash: true
  theme_args:
    simple_style: auto

enabled_plugins:
  - 'Hash plugin'
  - 'Search on category select'
  - 'Self Informations'
  - 'Tracker URL remover'
  - 'Open Access DOI rewrite'

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    
  - name: wikipedia
    engine: wikipedia
    shortcut: wiki
    weight: 2
    
  - name: github
    engine: github
    shortcut: gh

locales:
  en: English
  de: Deutsch
  fr: Français
  es: Español

doi_resolvers:
  oadoi.org: 'https://oadoi.org/'
  doi.org: 'https://doi.org/'

default_doi_resolver: 'oadoi.org'

default_cookies:
  - name: autocomplete
    value: "duckduckgo"
  - name: language
    value: "en-US"
  - name: safesearch
    value: "0"
  - name: theme
    value: "simple"