services:
  ollama-pull:
    image: ${OLLAMA_PULL_IMAGE}
    container_name: ${PROJECT_NAME}-ollama-pull
    restart: "no"
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend-bridge-network
    environment:
      PGHOST: supabase-db
      PGPORT: 5432
      PGDATABASE: ${SUPABASE_DB_NAME}
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
      OLLAMA_HOST_URL: http://host.docker.internal:11434
    volumes:
      - ./ollama-pull/scripts:/scripts
    entrypoint: ["/scripts/pull.sh"]

  comfyui-init:
    image: ${COMFYUI_INIT_IMAGE}
    container_name: ${PROJECT_NAME}-comfyui-init
    restart: "no"
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      ollama-pull:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - backend-bridge-network
    environment:
      PGHOST: supabase-db
      PGPORT: 5432
      PGDATABASE: ${SUPABASE_DB_NAME}
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
      COMFYUI_MODELS_PATH: /models
      COMFYUI_HOST_URL: ${COMFYUI_HOST_URL:-http://host.docker.internal:8000}
      COMFYUI_LOCAL_MODELS_PATH: ${COMFYUI_LOCAL_MODELS_PATH:-/Users/kaveh/Documents/ComfyUI/models}
      IS_LOCAL_COMFYUI: "true"
    volumes:
      - ./comfyui-init/scripts:/scripts
      - comfyui-models:/models
      - ${COMFYUI_LOCAL_MODELS_PATH:-/Users/kaveh/Documents/ComfyUI/models}:/host_models
    entrypoint: ["/scripts/download_models.sh"]


  local-deep-researcher:
    build:
      context: ./local-deep-researcher
      args:
        BASE_IMAGE: ${LOCAL_DEEP_RESEARCHER_IMAGE}
    container_name: ${PROJECT_NAME}-local-deep-researcher
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      ollama-pull:
        condition: service_completed_successfully
      searxng:
        condition: service_healthy
      comfyui-init:
        condition: service_completed_successfully
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Database connection for LLM config
      DATABASE_URL: postgresql://${SUPABASE_DB_USER}:${SUPABASE_DB_PASSWORD}@supabase-db:5432/${SUPABASE_DB_NAME}
      # Ollama connection (local host)
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      # Search configuration
      SEARCH_API: ${LOCAL_DEEP_RESEARCHER_SEARCH_API:-searxng}
      SEARXNG_URL: http://searxng:8080
      MAX_WEB_RESEARCH_LOOPS: ${LOCAL_DEEP_RESEARCHER_LOOPS:-3}
    ports:
      - "${LOCAL_DEEP_RESEARCHER_PORT}:2024"
    volumes:
      - local-deep-researcher-data:/app/data
    networks:
      - backend-bridge-network

  searxng:
    image: ${SEARXNG_IMAGE}
    container_name: ${PROJECT_NAME}-searxng
    restart: unless-stopped
    networks:
      - backend-bridge-network
    ports:
      - "${SEARXNG_PORT}:8080"
    volumes:
      - ./searxng/config:/etc/searxng:rw
      - searxng-data:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:${SEARXNG_PORT}
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - FORCE_OWNERSHIP=1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  n8n:
    image: ${N8N_IMAGE}
    container_name: ${PROJECT_NAME}-n8n
    restart: unless-stopped
    depends_on:
      supabase-db-init:
        condition: service_completed_successfully
      ollama-pull:
        condition: service_completed_successfully
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: supabase-db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${SUPABASE_DB_NAME}
      DB_POSTGRESDB_USER: ${SUPABASE_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${SUPABASE_DB_PASSWORD}
      DB_POSTGRESDB_SCHEMA: n8n
      DB_SCHEMA: n8n
      N8N_HOST: ${N8N_HOST:-localhost}
      N8N_PORT: 5678
      N8N_PROTOCOL: ${N8N_PROTOCOL:-http}
      N8N_PROXY_HOPS: 1
      WEBHOOK_URL: http://n8n.localhost:${KONG_HTTP_PORT}/
      NODE_ENV: production
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_AUTH_ENABLED: ${N8N_AUTH_ENABLED:-true}
      N8N_BASIC_AUTH_ACTIVE: ${N8N_BASIC_AUTH_ACTIVE:-true}
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_SECURE_COOKIE: false
      N8N_RUNNERS_ENABLED: true
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      NODE_OPTIONS: --max_old_space_size=512
      EXECUTIONS_MODE: ${N8N_EXECUTIONS_MODE:-queue}
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      QUEUE_BULL_REDIS_DB: 0
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - backend-bridge-network


volumes:
  local-deep-researcher-data:
  searxng-data:
  n8n-data:
  comfyui-models:
  comfyui-output:
  comfyui-input:
  comfyui-custom-nodes: