services:
  weaviate-init:
    image: ${WEAVIATE_INIT_IMAGE:-alpine:latest}
    container_name: ${PROJECT_NAME}-weaviate-init
    restart: "no"
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      PGHOST: supabase-db
      PGPORT: 5432
      PGDATABASE: ${SUPABASE_DB_NAME}
      PGUSER: ${SUPABASE_DB_USER}
      PGPASSWORD: ${SUPABASE_DB_PASSWORD}
    volumes:
      - ./weaviate-init/scripts:/scripts
      - weaviate-shared-config:/shared
    networks:
      - backend-bridge-network
    entrypoint: ["/scripts/init-weaviate.sh"]

  weaviate:
    image: ${WEAVIATE_IMAGE}
    container_name: ${PROJECT_NAME}-weaviate
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
      ollama:
        condition: service_started
      weaviate-init:
        condition: service_completed_successfully
      multi2vec-clip:
        condition: service_started
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,text2vec-openai,multi2vec-clip,generative-ollama,generative-openai'
      CLUSTER_HOSTNAME: 'weaviate'
      OLLAMA_ENDPOINT: 'http://ollama:11434'
      OPENAI_APIKEY: ${OPENAI_API_KEY:-}
      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
    entrypoint: ["/scripts/configure-weaviate.sh", "/bin/weaviate", "--host", "0.0.0.0", "--port", "8080", "--scheme", "http"]
    ports:
      - "${WEAVIATE_PORT}:8080"
      - "${WEAVIATE_GRPC_PORT}:50051"
    volumes:
      - weaviate-data:/var/lib/weaviate
      - weaviate-shared-config:/shared
      - ./weaviate-init/scripts:/scripts
    networks:
      - backend-bridge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  multi2vec-clip:
    image: ${MULTI2VEC_CLIP_IMAGE}
    container_name: ${PROJECT_NAME}-multi2vec-clip
    restart: unless-stopped
    depends_on:
      supabase-db:
        condition: service_healthy
    environment:
      ENABLE_CUDA: '0'
    networks:
      - backend-bridge-network

volumes:
  weaviate-data:
    driver: local
  weaviate-shared-config:
    driver: local